version: "3.8"
services:
  db:
    image: postgres:15.2
    container_name: sectors-db
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sectors
      POSTGRES_USER: sector
      POSTGRES_PASSWORD: secret
  app:
    build: .
    container_name: sectors-app
    ports:
      - "8088:8088"
    expose:
      - "8088"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: jdbc:postgresql://db:5432/sectors
      POSTGRES_USER: sector
      POSTGRES_PASSWORD: secret
volumes:
  postgres_data: