--liquibase formatted sql

--changeset digid0c:init_sectors_structure logicalFilePath:db/changelog/changes/40
INSERT INTO sector (name, parent_id) VALUES ('Manufacturing', null);
INSERT INTO sector (name, parent_id) VALUES ('Construction materials', 1);
INSERT INTO sector (name, parent_id) VALUES ('Electronics and Optics', 1);
INSERT INTO sector (name, parent_id) VALUES ('Food and Beverage', 1);
INSERT INTO sector (name, parent_id) VALUES ('Bakery & confectionery products', 4);
INSERT INTO sector (name, parent_id) VALUES ('Beverages', 4);
INSERT INTO sector (name, parent_id) VALUES ('Fish & fish products', 4);
INSERT INTO sector (name, parent_id) VALUES ('Meat & meat products', 4);
INSERT INTO sector (name, parent_id) VALUES ('Milk & dairy products', 4);
INSERT INTO sector (name, parent_id) VALUES ('Other', 4);
INSERT INTO sector (name, parent_id) VALUES ('Sweets & snack food', 4);
INSERT INTO sector (name, parent_id) VALUES ('Furniture', 1);
INSERT INTO sector (name, parent_id) VALUES ('Bathroom/sauna', 12);
INSERT INTO sector (name, parent_id) VALUES ('Bedroom', 12);
INSERT INTO sector (name, parent_id) VALUES ('Children’s room', 12);
INSERT INTO sector (name, parent_id) VALUES ('Kitchen', 12);
INSERT INTO sector (name, parent_id) VALUES ('Living room', 12);
INSERT INTO sector (name, parent_id) VALUES ('Office', 12);
INSERT INTO sector (name, parent_id) VALUES ('Other (Furniture)', 12);
INSERT INTO sector (name, parent_id) VALUES ('Outdoor', 12);
INSERT INTO sector (name, parent_id) VALUES ('Project furniture', 12);
INSERT INTO sector (name, parent_id) VALUES ('Machinery', 1);
INSERT INTO sector (name, parent_id) VALUES ('Machinery components', 22);
INSERT INTO sector (name, parent_id) VALUES ('Machinery equipment/tools', 22);
INSERT INTO sector (name, parent_id) VALUES ('Manufacture of machinery', 22);
INSERT INTO sector (name, parent_id) VALUES ('Maritime', 22);
INSERT INTO sector (name, parent_id) VALUES ('Aluminium and steel workboats', 26);
INSERT INTO sector (name, parent_id) VALUES ('Boat/Yacht building', 26);
INSERT INTO sector (name, parent_id) VALUES ('Ship repair and conversion', 26);
INSERT INTO sector (name, parent_id) VALUES ('Metal structures', 22);
INSERT INTO sector (name, parent_id) VALUES ('Other', 22);
INSERT INTO sector (name, parent_id) VALUES ('Repair and maintenance service', 22);
INSERT INTO sector (name, parent_id) VALUES ('Metalworking', 1);
INSERT INTO sector (name, parent_id) VALUES ('Construction of metal structures', 33);
INSERT INTO sector (name, parent_id) VALUES ('Houses and buildings', 33);
INSERT INTO sector (name, parent_id) VALUES ('Metal products', 33);
INSERT INTO sector (name, parent_id) VALUES ('Metal works', 33);
INSERT INTO sector (name, parent_id) VALUES ('CNC-machining', 37);
INSERT INTO sector (name, parent_id) VALUES ('Forgings, Fasteners', 37);
INSERT INTO sector (name, parent_id) VALUES ('Gas, Plasma, Laser cutting', 37);
INSERT INTO sector (name, parent_id) VALUES ('MIG, TIG, Aluminum welding', 37);
INSERT INTO sector (name, parent_id) VALUES ('Plastic and Rubber', 1);
INSERT INTO sector (name, parent_id) VALUES ('Packaging', 42);
INSERT INTO sector (name, parent_id) VALUES ('Plastic goods', 42);
INSERT INTO sector (name, parent_id) VALUES ('Plastic processing technology', 42);
INSERT INTO sector (name, parent_id) VALUES ('Blowing', 45);
INSERT INTO sector (name, parent_id) VALUES ('Moulding', 45);
INSERT INTO sector (name, parent_id) VALUES ('Plastics welding and processing', 45);
INSERT INTO sector (name, parent_id) VALUES ('Plastic profiles', 42);
INSERT INTO sector (name, parent_id) VALUES ('Printing', 1);
INSERT INTO sector (name, parent_id) VALUES ('Advertising', 50);
INSERT INTO sector (name, parent_id) VALUES ('Book/Periodicals printing', 50);
INSERT INTO sector (name, parent_id) VALUES ('Labelling and packaging printing', 50);
INSERT INTO sector (name, parent_id) VALUES ('Textile and Clothing', 1);
INSERT INTO sector (name, parent_id) VALUES ('Clothing', 54);
INSERT INTO sector (name, parent_id) VALUES ('Textile', 54);
INSERT INTO sector (name, parent_id) VALUES ('Wood', 1);
INSERT INTO sector (name, parent_id) VALUES ('Other (Wood)', 57);
INSERT INTO sector (name, parent_id) VALUES ('Wooden building materials', 57);
INSERT INTO sector (name, parent_id) VALUES ('Wooden houses', 57);
INSERT INTO sector (name, parent_id) VALUES ('Other', null);
INSERT INTO sector (name, parent_id) VALUES ('Creative industries', 61);
INSERT INTO sector (name, parent_id) VALUES ('Energy technology', 61);
INSERT INTO sector (name, parent_id) VALUES ('Environment', 61);
INSERT INTO sector (name, parent_id) VALUES ('Service', null);
INSERT INTO sector (name, parent_id) VALUES ('Business services', 65);
INSERT INTO sector (name, parent_id) VALUES ('Engineering', 65);
INSERT INTO sector (name, parent_id) VALUES ('Information Technology and Telecommunications', 65);
INSERT INTO sector (name, parent_id) VALUES ('Data processing, Web portals, E-marketing', 68);
INSERT INTO sector (name, parent_id) VALUES ('Programming, Consultancy', 68);
INSERT INTO sector (name, parent_id) VALUES ('Software, Hardware', 68);
INSERT INTO sector (name, parent_id) VALUES ('Telecommunications', 68);
INSERT INTO sector (name, parent_id) VALUES ('Tourism', 65);
INSERT INTO sector (name, parent_id) VALUES ('Translation services', 65);
INSERT INTO sector (name, parent_id) VALUES ('Transport and Logistics', 65);
INSERT INTO sector (name, parent_id) VALUES ('Air', 75);
INSERT INTO sector (name, parent_id) VALUES ('Rail', 75);
INSERT INTO sector (name, parent_id) VALUES ('Road', 75);
INSERT INTO sector (name, parent_id) VALUES ('Water', 75);
--rollback delete from sector;